project:
  type: book
  output-dir: ../docs/book

book:
  title: "Admin2 Severity Index Tool"
  author:
    - name: William Becker
      url: http://www.willbecker.me
  date: last-modified
  chapters:
    - index.qmd
    - about.qmd
    - part: "Using the app"
      chapters:
        - layout.qmd
        - data_input.qmd
        - user_geometry.qmd
        - analysis.qmd
        - results.qmd
        - profiles.qmd
        - scenarios.qmd
        - unit_comparison.qmd
        - map_builder.qmd
    - part: "Methodology"
      chapters:
        - meth_overview.qmd
        - data_processing.qmd
        - aggregation_weighting.qmd
        - technical_implementation.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



